
```
Benchmark           Mode  Cnt  Score   Error  Units
DemoBenchmark.busr  avgt   10  2.758 ± 0.093   s/op
DemoBenchmark.erka  avgt   10  2.423 ± 0.039   s/op
DemoBenchmark.conf  avgt   10  1.779 ± 0.018   s/op
DemoBenchmark.actr  avgt   10  1.430 ± 0.073   s/op
DemoBenchmark.demo  avgt   10  1.154 ± 0.056   s/op
DemoBenchmark.slim  avgt   10  1.112 ± 0.024   s/op
DemoBenchmark.thin  avgt   10  0.968 ± 0.027   s/op
DemoBenchmark.lite  avgt   10  0.813 ± 0.024   s/op
DemoBenchmark.func  avgt   10  0.742 ± 0.012   s/op
```

Legend:

* Busr: same as "conf" but adds Spring Cloud Bus and Rabbit
* Erka: same as "actr" sample but with Eureka client
* Conf: same as "actr" sample plus config client
* Actr: same as "demo" sample plus Actuator
* Demo: vanilla Spring Boot MVC app with one endpoint (no Actuator)
* Slim: same thing but explicitly `@Imports` all configuration
* Thin: reduce the `@Imports` down to a set of 4 that are needed for the endpoint
* Lite: copy the imports from "thin" and make them into hard-coded, unconditional configuration
* Func: extract the configuration methods from "lite" and register bits of it using the function bean API

N.B. The "thin" sample has `@EnableWebMvc` (implicitly), but "lite"
and "func" pulled the relevant features of that out into a separate
class (so a few beans were dropped).

|===
| sample | configs | beans | startup(millis)

| busr | 151| 389 | 2758
| erka | 127| 310 | 2423
| conf | 100| 245 | 1779
| actr | 72 | 183 | 1430
| demo | 32 | 108 | 1154
| slim | 31 | 103 | 1112
| thin | 14 | 60  | 968
| lite | 4  | 30  | 813
| func | 1  | 25  | 742

|===

== Laptop (carbon)

```
Benchmark           Mode  Cnt  Score   Error  Units
DemoBenchmark.demo  avgt   10  1.697 ± 0.081   s/op
DemoBenchmark.slim  avgt   10  1.673 ± 0.098   s/op
DemoBenchmark.thin  avgt   10  1.446 ± 0.061   s/op
DemoBenchmark.lite  avgt   10  1.203 ± 0.072   s/op
DemoBenchmark.func  avgt   10  1.150 ± 0.056   s/op
```