[.lead]
In this module we study the effect of Spring and Spring Boot on startup time using the webflux and functional webflux programming models.

```
class        method sample  beans   classes   heap    memory  median  mean  range
MainBenchmark  main  jlog  158.000  3671.000  6.580   44.277  0.693  0.698  0.005
MainBenchmark  main  demo  184.000  4449.000  8.362   50.860  0.787  0.803  0.018
MainBenchmark  main  actr  370.000  5241.000  9.993   56.583  0.943  0.960  0.016
MainBenchmark  main  jdbc  264.000  5124.000  9.171   55.068  0.885  0.897  0.015
MainBenchmark  main  actj  454.000  5423.000  9.887   57.530  1.021  1.036  0.028
MiniBenchmark  boot  jlog  112.000  3255.000  6.739   41.243  0.571  0.576  0.006
MiniBenchmark  boot  demo  56.000   3936.000  6.381   45.139  0.669  0.679  0.017
MiniBenchmark  mini  jlog  108.000  2990.000  5.448   38.589  0.510  0.518  0.010
MiniBenchmark  mini  demo  81.000   3664.000  6.015   43.440  0.613  0.623  0.021
MiniBenchmark  micro jlog  8.000    2211.000  4.800   33.275  0.337  0.344  0.011
MiniBenchmark  micro demo  8.000    2944.000  7.497   40.718  0.440  0.449  0.012
```

.Number of Classes vs. Startup Time
image::https://docs.google.com/spreadsheets/d/e/2PACX-1vR8B4l5WkWf-9gZWmIYTkmBWM7YWf5bRg852OakrV0G2-vtfM_UkVNRC3cTVk1079HagnMVHYZnvbib/pubchart?oid=976086548&format=image[]

Notes:

* The `MainBenchmark.main(demo)` is full Boot + Webflux + autoconfiguration.
* The `boot` samples use Spring Boot but no autoconfiguration.
* The `jlog` samples exclude logback as well as Hibernate Validator and Jackson.
* The `mini` samples do not use Spring Boot (just `@EnableWebFlux`).
* The `micro` samples do not use `@EnableWebflux`, just a manual route registration.

Non-heap is really what matters for these smaller apps.

There's a flag in Spring Boot 2.2 that makes all beans lazy by
default. It is switched on in all the above benchmarks.
Some of those beans end up being initialized on
the first HTTP request, but probably most of them are not needed in
this sample, so they could stay uninitialized and no-one would
care. We'd need more logic / conditions in `@EnableWebFlux` to
capitalize on it without cheating

== Open J9

The results are quite variable with Open J9, but once the CDS cache is
created you usually see about 10-15% improvement.

== Old Results

Comparison of different Webflux options in Spring Boot 2.0:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units Webstack
MainBenchmark.main      demo    ss   10  1.124 ± 0.050   s/op mvc
MainBenchmark.main      flux    ss   10  1.023 ± 0.080   s/op webflux
MainBenchmark.main      actr    ss   10  1.548 ± 0.049   s/op mvc
MainBenchmark.main      demo    ss   10  0.993 ± 0.027   s/op flux.fn
MainBenchmark.main      actr    ss   10  1.397 ± 0.068   s/op webflux
```

Summary: webflux.fn and @webflux are comparable, and both are faster on Netty than MVC on Tomcat (>~10%).

=== Spring Boot 2.1.0

Spring 5.1 had some performance improvements.

```
Benchmark            (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main       empt    ss   10  0.596 ± 0.010   s/op
MainBenchmark.main       jlog    ss   10  0.770 ± 0.022   s/op
MainBenchmark.main       demo    ss   10  0.939 ± 0.037   s/op
MainBenchmark.main       actr    ss   10  1.270 ± 0.025   s/op
MainBenchmark.main       jdbc    ss   10  1.057 ± 0.018   s/op
MainBenchmark.main       actj    ss   10  1.449 ± 0.059   s/op
MiniBenchmark.boot       jlog    ss   10  0.458 ± 0.007   s/op
MiniBenchmark.boot       demo    ss   10  0.572 ± 0.014   s/op
MiniBenchmark.micro      jlog    ss   10  0.199 ± 0.013   s/op
MiniBenchmark.micro      demo    ss   10  0.304 ± 0.003   s/op
MiniBenchmark.mini       jlog    ss   10  0.412 ± 0.022   s/op
MiniBenchmark.mini       demo    ss   10  0.529 ± 0.013   s/op
```

On J9:

```
MainBenchmark.main       empt    ss   10  0.455 ± 0.053   s/op
MainBenchmark.main       jlog    ss   10  0.644 ± 0.038   s/op
MainBenchmark.main       demo    ss   10  0.851 ± 0.026   s/op
MainBenchmark.main       actr    ss   10  1.231 ± 0.048   s/op
MainBenchmark.main       jdbc    ss   10  0.973 ± 0.040   s/op
MainBenchmark.main       actj    ss   10  1.389 ± 0.040   s/op
```