[.lead]
In this module we study the effect of Spring and Spring Boot on startup time using the webflux and functional webflux programming models.

```
class        method sample  beans   classes   heap    memory  median  mean  range
MainBenchmark  main  empt  24.000   3155.000  5.022  38.395  0.524  0.531  0.012
MainBenchmark  main  jlog  80.000   3649.000  6.540  44.006  0.685  0.712  0.046
MainBenchmark  main  demo  93.000   4420.000  8.153  50.333  0.771  0.816  0.042
MainBenchmark  main  actr  186.000  5183.000  9.208  55.256  0.924  0.941  0.015
MainBenchmark  main  jdbc  131.000  5077.000  8.633  54.062  0.862  0.877  0.018
MainBenchmark  main  actj  226.000  5340.000  9.350  56.265  0.988  0.997  0.010
MiniBenchmark  boot  jlog  28.000   3250.000  6.692  41.158  0.562  0.571  0.013
MiniBenchmark  boot  demo  28.000   3931.000  6.335  45.057  0.659  0.666  0.007
MiniBenchmark  mini  jlog  27.000   2986.000  5.421  38.561  0.516  0.524  0.014
MiniBenchmark  mini  demo  27.000   3660.000  5.976  43.370  0.612  0.623  0.023
MiniBenchmark  micro jlog  2.000    2215.000  4.817  33.320  0.339  0.344  0.007
MiniBenchmark  micro demo  2.000    2948.000  7.514  40.747  0.440  0.444  0.005
```

.Number of Classes vs. Startup Time
image::https://docs.google.com/spreadsheets/d/e/2PACX-1vQpSEfx0Y1W9aD3XVyn91-S0jtUp2DRCQSy_W_LMGyMR91YLAQ1mL7MiR1BRd8VzshvtuxzL6WAnlxf/pubchart?oid=1452854557&amp;format=image[]

Notes:

* The `MainBenchmark.main(demo)` is full Boot + Webflux + autoconfiguration.
* The `boot` samples use Spring Boot but no autoconfiguration.
* The `jlog` samples exclude logback as well as Hibernate Validator and Jackson.
* The `mini` samples do not use Spring Boot (just `@EnableWebFlux`).
* The `micro` samples do not use `@EnableWebflux`, just a manual route registration.

Non-heap is really what matters for these smaller apps.

There's a flag in Spring Boot 2.2 that makes all beans lazy by
default. It is switched on in all the above benchmarks.
Some of those beans end up being initialized on
the first HTTP request, but probably most of them are not needed in
this sample, so they could stay uninitialized and no-one would
care. We'd need more logic / conditions in `@EnableWebFlux` to
capitalize on it without cheating

== Open J9

The results are quite variable with Open J9, but once the CDS cache is
created you usually see about 10-15% improvement.

== Old Results

Comparison of different Webflux options in Spring Boot 2.0:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units Webstack
MainBenchmark.main      demo    ss   10  1.124 ± 0.050   s/op mvc
MainBenchmark.main      flux    ss   10  1.023 ± 0.080   s/op webflux
MainBenchmark.main      actr    ss   10  1.548 ± 0.049   s/op mvc
MainBenchmark.main      demo    ss   10  0.993 ± 0.027   s/op flux.fn
MainBenchmark.main      actr    ss   10  1.397 ± 0.068   s/op webflux
```

Summary: webflux.fn and @webflux are comparable, and both are faster on Netty than MVC on Tomcat (>~10%).

=== Spring Boot 2.1.0

Spring 5.1 had some performance improvements.

```
Benchmark            (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main       empt    ss   10  0.596 ± 0.010   s/op
MainBenchmark.main       jlog    ss   10  0.770 ± 0.022   s/op
MainBenchmark.main       demo    ss   10  0.939 ± 0.037   s/op
MainBenchmark.main       actr    ss   10  1.270 ± 0.025   s/op
MainBenchmark.main       jdbc    ss   10  1.057 ± 0.018   s/op
MainBenchmark.main       actj    ss   10  1.449 ± 0.059   s/op
MiniBenchmark.boot       jlog    ss   10  0.458 ± 0.007   s/op
MiniBenchmark.boot       demo    ss   10  0.572 ± 0.014   s/op
MiniBenchmark.micro      jlog    ss   10  0.199 ± 0.013   s/op
MiniBenchmark.micro      demo    ss   10  0.304 ± 0.003   s/op
MiniBenchmark.mini       jlog    ss   10  0.412 ± 0.022   s/op
MiniBenchmark.mini       demo    ss   10  0.529 ± 0.013   s/op
```

On J9:

```
MainBenchmark.main       empt    ss   10  0.455 ± 0.053   s/op
MainBenchmark.main       jlog    ss   10  0.644 ± 0.038   s/op
MainBenchmark.main       demo    ss   10  0.851 ± 0.026   s/op
MainBenchmark.main       actr    ss   10  1.231 ± 0.048   s/op
MainBenchmark.main       jdbc    ss   10  0.973 ± 0.040   s/op
MainBenchmark.main       actj    ss   10  1.389 ± 0.040   s/op
```